### ISSUE TITLE
Returning data from server to populate the Dropbox

### ISSUE THREAD

**Issue by zolfj** [softsimon/ngx-bootrap-multiselect#193]
Hello there,

I am trying to implement the Dropbox and am able to load data and save to db the selected dropbox value. My requirement is to only select 1 data from the dropbox. But for reason i get this error when I try to display the data got from the backend server in the dropbox. I get the following error. Can someone please help me to resolve the issue.

```
**Component**

myOptions_Shelflife: IMultiSelectOption[] = [];
 this.productForm.controls['shelflife'].valueChanges
      .subscribe((selectedOptions) => {
        console.log("INSIDE DROPBOXXXXXX PRODUCT!!!!!! " + selectedOptions);
        //console.log("ZZZZZZZZZZZZZZZ   " + JSON.stringify(this.myOptions_Shelflife));
      });

**Template.HTML**

<div class="form-group row">
              <label for="shelflife" class="col-md-4 col-form-label">Shelf Life (Month) <span class="required">*</span>
              <div *ngIf="(productForm.get('shelflife').touched ||
                                                             productForm.get('shelflife').dirty) &&
                                                             productForm.get('shelflife').errors">
                  <ul class="parsley-errors-list filled" id="parsley-id-5"><li class="parsley-required">This value is required</li></ul>
                </div>
              </label>
              <div class="col-md-7">
                <ss-multiselect-dropdown [options]="myOptions_Shelflife" [texts]="myTexts" [settings]="mySettings"  [(ngModel)]="optionsModel" (ngModelChange)="onChange($event)"
                                         formControlName="shelflife"></ss-multiselect-dropdown>
              </div>
          </div>
```

ERROR Error: Error trying to diff '1'. Only arrays and iterables are allowed
    at DefaultIterableDiffer.diff (http://localhost:3002/vendor.bundle.js:57473:19) [angular]
    at MultiselectDropdown.ngDoCheck (http://localhost:3002/5.chunk.js:9320:35) [angular]
    at checkAndUpdateDirectiveInline (http://localhost:3002/vendor.bundle.js:61208:19) [angular]
    at checkAndUpdateNodeInline (http://localhost:3002/vendor.bundle.js:62628:17) [angular]
    at checkAndUpdateNode (http://localhost:3002/vendor.bundle.js:62567:16) [angular]
    at debugCheckAndUpdateNode (http://localhost:3002/vendor.bundle.js:63270:59) [angular]
    at debugCheckDirectivesFn (http://localhost:3002/vendor.bundle.js:63211:13) [angular]
    at Object.View_ProductEditComponent_0.co [as updateDirectives] (ng:///MasterModule/ProductEditComponent.ngfactory.js:3251:5) [angular]
    at Object.debugUpdateDirectives [as updateDirectives] (http://localhost:3002/vendor.bundle.js:63196:21) [angular]
    at checkAndUpdateView (http://localhost:3002/vendor.bundle.js:62534:14) [angular]
    at callViewAction (http://localhost:3002/vendor.bundle.js:62897:21) [angular]

**Comment by chris--jones** [comment]
This example doesn't seem to show how you're setting `myOptions_Shelflife` so it's hard to diagnose.
Can you provide more context?
